FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Celery worker
CMD ["celery", "-A", "interfaces.task_runner", "worker", "--loglevel=info", "--broker=redis://redis:6379/0"]
